config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root 'movies#index'
  resources :movies do
    resources :seances, except: %i[show index] do
      resources :reservations
    end
  end
  resources :seances
  resources :reservations, except: %i[edit update] do
    collection do
      get '/find_by_user', to: "reservations#find_by_user"
      get '/find_by_seance', to: "reservations#find_by_seance"
      post 'create_as_manager', to: 'reservations#create_as_manager'
      post 'create_as_guest', to: 'reservations#create_as_guest'
    end
    patch 'cancel', on: :member
    patch 'confirm', on: :member
  end
  resources :halls, except: :show
  resources :discounts, except: :show
end

app/models/hall.rb
class Hall < ApplicationRecord
  has_many :seances, dependent: :destroy

  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true, uniqueness: true
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  include Pundit::Authorization

  before_action :set_hall, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    authorize Hall
    @halls = Hall.all
  end

  def new
    authorize Hall
    @hall = Hall.new
  end

  def edit
    authorize Hall
  end

  def create
    authorize Hall
    @hall = Hall.new(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to halls_url, notice: "Hall was successfully created." }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @hall
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to halls_url, notice: "Hall was successfully updated." }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @hall
    @hall.destroy

    respond_to do |format|
      format.html { redirect_to halls_url, notice: "Hall was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_hall
    @hall = Hall.find(params[:id])
  end

  def hall_params
    params.require(:hall).permit(:capacity, :name)
  end
end

app/views/halls/_form.html.erb
<%= form_with(model: hall) do |form| %>
  <% if hall.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hall.errors.count, "error") %> prohibited this hall from being saved:</h2>

      <ul>
        <% hall.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div style="margin-top: 1%;">
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
  <div>
    <%= link_to "Back to halls", halls_path, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/halls/_hall.html.erb
<div id="<%= dom_id hall %>">
  <p>
    <strong>Capacity:</strong>
    <%= hall.capacity %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= hall.name %>
  </p>
</div>

app/views/halls/edit.html.erb
<h1>Editing hall</h1>

<%= render "form", hall: @hall %>

<br>

app/views/halls/index.html.erb
<h1>Halls</h1>

<%= link_to "New hall", new_hall_path, class: "btn btn-outline-success"%>

<div id="halls">
  <% @halls.each do |hall| %>
  <div class="border border-dark container-fluid" style="float:left; margin: 2%; width: 15%;">
    <%= render hall %>
    <p>
      <%= link_to "Edit this hall", edit_hall_path(hall), class: "btn btn-outline-secondary" %> 
      <% if policy(hall).destroy? %>
        <%= button_to "Destroy this hall", hall, method: :delete, class: "btn btn-outline-danger" %>
      <% end %>
    </p>
  </div>
  <% end %>
</div>

app/views/halls/new.html.erb
<h1>New hall</h1>

<%= render "form", hall: @hall %>

<br>