config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root 'movies#index'
  resources :movies do
    resources :seances, except: %i[show index] do
      resources :reservations
    end
  end
  resources :seances
  resources :reservations, except: %i[edit update] do
    collection do
      get '/find_by_user', to: "reservations#find_by_user"
      get '/find_by_seance', to: "reservations#find_by_seance"
      post 'create_as_manager', to: 'reservations#create_as_manager'
      post 'create_as_guest', to: 'reservations#create_as_guest'
    end
    patch 'cancel', on: :member
    patch 'confirm', on: :member
  end
  resources :halls, except: :show
  resources :discounts, except: :show
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include Pundit::Authorization

  before_action :set_movie, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    authorize Movie
    @movies = Movie.all
    @discounts = Discount.all
  end

  def show
    authorize @movie
    @seances = Seance
               .where(movie_id: params[:id])
               .where(start_time: 30.minutes.from_now..7.days.from_now)
               .order(start_time: :asc)
  end

  def new
    authorize Movie
    @movie = Movie.new
  end

  def edit
    authorize Movie
  end

  def create
    authorize Movie
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @movie
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @movie
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:name, :description, :duration)
  end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div style="margin-top: 1%">
    <%= form.submit class: 'btn btn-outline-success'%>
  </div>
  <div>
    <%= link_to "Back to movies", movies_path, class: "btn btn-outline-secondary" %>
  </div>

<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <div>
    <div class="container-fluid" style="padding-top:1%;">
      <p>
        <strong>Name:</strong>
        <%= movie.name %>
      </p>

      <p>
        <strong>Duration:</strong>
        <%= movie.duration %>
      </p>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<h1 style="text-align: center; margin-bottom: 2%;">Movies</h1>

<% if @current_user.present? %>
  <% if policy(Movie).new? %>
    <%= link_to "New movie", new_movie_path, class: "btn btn-outline-success"%>
  <% end %>

  <% if policy(Hall).index? %>
    <%= link_to "Check halls", halls_path, class: "btn btn-outline-secondary"%>
  <% end %>

  <% if policy(Discount).index? %>
    <%= link_to "Check discounts", discounts_path, class: "btn btn-outline-secondary"%>
  <% end %>
<% end %>

<div id="movies" style="margin-top: 1%;">
  <% @movies.each do |movie| %>
    <div class="border border-dark" style="float:left; margin-right: 2%; margin-bottom:2%; width: 31%;">
      <%= render movie %>
      <div style="margin-left: 2%;">
      <%= link_to "Check seances", movie, class: "btn btn-outline-primary" %>

      <% if @current_user.present? %>
        <% if policy(Movie).edit? %>
          <%= link_to "Edit", edit_movie_path(movie), class: "btn btn-outline-secondary" %> 
        <% end %>
        
        <% if policy(Movie).destroy? %>
          <%= button_to "Destroy", movie, method: :delete,
           form_class: "myButtonForm", class: "btn btn-outline-danger"  %>
        <% end %>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

<div style="clear: left;">
  <h3 style="text-align: center; margin-bottom: 2%;">Discounts avaliabe:</h3>

  <div>
    <% @discounts.each do |discount| %>
      <div class="border border-dark" style="float:left; margin-right: 1%; margin-bottom:2%; width: 15%;">
        <%= render discount %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<div style="text-align: center;"> 
  <%= render @movie %>
  <div class="container-fluid">
    <p>
        <strong>Description:</strong>
        <%= @movie.description %>
    </p>
  
    <% if @current_user.present? %>
      <% if policy(Seance).new? %>
        <%= link_to "New seance", new_seance_path(movie_id: @movie.id), class: "btn btn-outline-success"%>
      <% end %>
    <% end %>
  </div>
</div>

<div style="margin-left:10%; padding-top: 1%;"> 
  <% @seances.each do |seance| %>
  <div class="border border-dark" style="float:left; margin-right: 2%; margin-bottom:2%; width: 15%;">
      <%= render seance %>

      <%= link_to "Make reservation", new_reservation_path(seance_id: seance.id), class: "btn btn-outline-success" %> 
      
      <% if @current_user.present? %>

        <% if policy(Reservation).find_by_seance?%>
          <%= link_to "Check reservations", find_by_seance_reservations_path(seance_id: seance.id), class: "btn btn-outline-secondary" %>
        <% end %>

        <% if policy(seance).edit? %>
          <%= link_to "Edit", edit_seance_path(seance), class: "btn btn-outline-secondary" %> 
        <% end %>
    
        <% if policy(Seance).destroy? %>
          <%= button_to "Destroy", seance, method: :delete, class: "btn btn-outline-danger" %>
        <% end %>
      <% end %>
  </div>
  <% end %>
</div>