config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root 'movies#index'
  resources :movies do
    resources :seances, except: %i[show index] do
      resources :reservations
    end
  end
  resources :seances
  resources :reservations, except: %i[edit update] do
    collection do
      get '/find_by_user', to: "reservations#find_by_user"
      get '/find_by_seance', to: "reservations#find_by_seance"
      post 'create_as_manager', to: 'reservations#create_as_manager'
      post 'create_as_guest', to: 'reservations#create_as_guest'
    end
    patch 'cancel', on: :member
    patch 'confirm', on: :member
  end
  resources :halls, except: :show
  resources :discounts, except: :show
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :seance
  belongs_to :user, optional: true
  belongs_to :discount, optional: true
  has_many :tickets, dependent: :destroy

  validates :status, presence: true
  validates :seats, presence: true
  validates :email, presence: true
  validates_format_of :email, with: Devise.email_regexp
  enum status: { reserved: 0, confirmed: 1, canceled: 2 }
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include Pundit::Authorization
  rescue_from ChangeStatusError, with: :change_status_error
  rescue_from NoUserForEmailError, with: :user_not_found

  before_action :set_reservation, only: %i[show destroy cancel confirm]
  before_action :authenticate_user!, except: %i[new create_as_guest]

  def find_by_user
    authorize Reservation
    reservations_for_user(find_user_by_email!(params[:email]))
    render template: "reservations/index"
  end

  def find_by_seance
    authorize Reservation
    @reservations = reservations_for_seance(params[:seance_id])
    render template: "reservations/index"
  end

  def cancel
    authorize @reservation
    raise ChangeStatusError unless @reservation.status == 'reserved'

    change_status(status: :canceled)
  end

  def confirm
    authorize @reservation
    raise ChangeStatusError unless @reservation.status == 'reserved'

    change_status(status: :confirmed)
  end

  def index
    authorize Reservation
    reservations_for_user(current_user.id)
  end

  def show
    authorize @reservation
  end

  def new
    authorize Reservation
    @reservation = Reservation.new(seance_id: params[:seance_id])
    @reservation.email = current_user.email if current_user.present?
    params_for_form(params[:seance_id])
  end

  def create
    authorize Reservation
    @reservation = Reservations::Create.new(**{ user_id: current_user.id, email: current_user.email,
                                                  seance_id: reservation_params[:seance_id], seats: reservation_params[:seats], status: :reserved })

    create_call(@reservation)
  end

  def create_as_manager
    authorize Reservation
    @reservation = Reservations::Create.new(**{ user_id: current_user.id, email: current_user.email,
                                                  seance_id: reservation_params[:seance_id], seats: reservation_params[:seats], status: :confirmed })

    create_call(@reservation)
  end

  def create_as_guest
    authorize Reservation
    @reservation = Reservations::Create.new(**{ email: reservation_params[:email], seance_id: reservation_params[:seance_id], seats: reservation_params[:seats], status: :reserved })

    create_call(@reservation)
  end

  def destroy
    authorize @reservation
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def taken_seats(seance_id)
    @taken_seats = []
    Reservation.where(seance_id:).where.not(status: :canceled)
               .where.not(id: @reservation.id)
               .order(seats: :asc).pluck(:seats).each do |seat|
      @taken_seats |= seat
    end
    @taken_seats.sort!
  end

  def params_for_form(seance_id)
    taken_seats(seance_id)
    @capacity = Seance.where(id: seance_id)
                      .includes(:hall).pluck(:capacity)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:seance_id, :email, seats: [])
  end

  def find_user_by_email!(email)
    raise NoUserForEmailError unless User.find_by(email:)
  end

  def reservations_for_user(user_id)
    @reservations = Reservation.where(user_id:)
                               .joins(:seance).includes({ seance: [:movie] }, :discount)
                               .order(start_time: :desc)
  end

  def reservations_for_seance(seance_id)
    Reservation.where(seance_id:)
               .includes({ seance: [:movie] }, :discount)
  end

  def change_status(status)
    respond_to do |format|
      if @reservation.update(status)
        format.html { redirect_to reservation_url(@reservation), notice: "Status was successfully changed." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_call(reservation)
    if reservation.call
      redirect_to movies_path, notice: "Reservation successfully created"
    else
      redirect_to root_path, alert: reservation.errors
    end
  end

  def change_status_error
    flash[:alert] = "Cannot update status."
    redirect_back(fallback_location: reservations_path)
  end

  def user_not_found
    flash[:alert] = "No user with given email"
    redirect_back(fallback_location: root_path)
  end
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :seance_id %>

  <% if !current_user.present? %>
    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email %>
    </div>
    <% end %>

  <p>
    <strong>Hall seats:</strong>
    <%= "1 to #{@capacity}" %>
  </p>

  <p>
    <strong>Seats taken:</strong>
    <%= @taken_seats %>
  </p>

  <div id="newSeat" style="margin-top: 1%;" class="btn" > + </div>

  <div id="seats">
    <div id="seat">
      <%= form.label :seats, style: "display: block" %>
      <%= form.number_field :seats, multiple: true%>
    </div>
  </div>

  <div style="margin-top: 1%">
    <% if !current_user.present? %>
      <%= form.submit "Make a reservation", formaction: create_as_guest_reservations_path, class: "btn btn-outline-success" %>
    <% elsif current_user.manager? %>
      <%= form.submit "Make a reservation", formaction: create_as_manager_reservations_path, class: "btn btn-outline-success" %>
    <%else%>
      <%= form.submit "Make a reservation", class: "btn btn-outline-success" %>
    <%end%>
  </div>
  
  <div>
    <%= link_to "Back to movies", movies_path, class: "btn btn-outline-secondary" %>
  </div>

  <div>
    <%= link_to "Back to reservations", reservations_path, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

<script>
  var count = 1;
  document.getElementById("newSeat").onclick = function(){
    if (count < 10){
      document.getElementById("seats").appendChild(document.getElementById("seat").cloneNode(true));
      count++;
    }
  }
</script>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Status:</strong>
    <%= reservation.status %>
  </p>

  <p>
    <strong>Seance:</strong>
    <%= reservation.seance.movie.name %>
  </p>

  <p>
    <strong>Seance time:</strong>
    <%= format_date(reservation.seance.start_time) %>
  </p>

  <p>
    <strong>User:</strong>
    <%= reservation.email %>
  </p>

  <p>
    <strong>Seats:</strong>
    <%= reservation.seats %>
  </p>

  <% if reservation.discount_id.present?%>
    <p>
      <strong>Snack bar discount:</strong>
      <%= "#{reservation.discount.value}%" %>
    </p>
  <% end %>

</div>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<% if policy(Reservation).find_by_user? %>
  <%= form_with url: "/reservations/find_by_user", method: :get do |form| %>
    <%= form.label :email, "Search for:" %>
    <%= form.text_field :email %>
    <%= form.submit "Search" %>
  <% end %>
<% end %>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <div class="border border-dark" style="margin-bottom:2%;">
      <%= render reservation %>
      <p>
        <% if policy(reservation).show? %>
          <%= link_to "Show", reservation_path(reservation), class: "btn btn-outline-secondary" %> 
        <% end %>
        <% if reservation.status == "reserved" %>
          <% if policy(reservation).cancel? %>
            <%= button_to "Cancel this reservation", cancel_reservation_path(id: reservation.id), method: :patch, class: "btn btn-outline-danger" %>
          <% end %>
          <% if policy(reservation).confirm? %>
            <%= button_to "Confirm this reservation", confirm_reservation_path(id: reservation.id), method: :patch, class: "btn btn-outline-success" %>
          <% end %>       
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

app/views/reservations/show.html.erb
<div style="text-align: center;" class="border border-dark" >
  <%= render @reservation %>

  <div>
    <% if policy(@reservation).destroy? %>
      <%= button_to "Destroy", @reservation, method: :delete,
        form_class: "myButtonForm", class: "btn btn-outline-danger"  %>
    <% end %>
    <%= link_to "Back to reservations", reservations_path, class: "btn btn-outline-secondary" %>
  </div>
</div>