config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root 'movies#index'
  resources :movies do
    resources :seances, except: %i[show index] do
      resources :reservations
    end
  end
  resources :seances
  resources :reservations, except: %i[edit update] do
    collection do
      get '/find_by_user', to: "reservations#find_by_user"
      get '/find_by_seance', to: "reservations#find_by_seance"
      post 'create_as_manager', to: 'reservations#create_as_manager'
      post 'create_as_guest', to: 'reservations#create_as_guest'
    end
    patch 'cancel', on: :member
    patch 'confirm', on: :member
  end
  resources :halls, except: :show
  resources :discounts, except: :show
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_many :reservations

  validates :tickets_needed, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :value, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  include Pundit::Authorization

  before_action :set_discount, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    authorize Discount
    @discounts = Discount.all
  end

  def new
    authorize Discount
    @discount = Discount.new
  end

  def edit
    authorize Discount
  end

  def create
    authorize Discount
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to discount_url(@discount), notice: "Discount was successfully created." }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @discount
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discount_url(@discount), notice: "Discount was successfully updated." }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @discount
    @discount.destroy

    respond_to do |format|
      format.html { redirect_to discounts_url, notice: "Discount was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_discount
    @discount = Discount.find(params[:id])
  end

  def discount_params
    params.require(:discount).permit(:tickets_needed, :value)
  end
end

app/views/discounts/_discount.html.erb
<div id="<%= dom_id discount %>">
  <p>
    <strong>Tickets needed:</strong>
    <%= discount.tickets_needed %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= "#{discount.value}%" %>
  </p>
</div>

app/views/discounts/_form.html.erb
<%= form_with(model: discount) do |form| %>
  <% if discount.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
        <% discount.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tickets_needed, style: "display: block" %>
    <%= form.number_field :tickets_needed %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div style="margin-top: 1%;">
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
  <div>
    <%= link_to "Back to discounts", discounts_path, class: "btn btn-outline-secondary" %>
  </div>  
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing discount</h1>

<%= render "form", discount: @discount %>

<br>

app/views/discounts/index.html.erb
<h1>Discounts</h1>

<%= link_to "New discount", new_discount_path, class: "btn btn-outline-success"%>

<div id="discounts">
  <% @discounts.each do |discount| %>
    <div class="border border-dark container-fluid" style="float:left; margin: 2%; width: 15%;">
      <%= render discount %>
      <p>
        <%= link_to "Edit this discount", edit_discount_path(discount), class: "btn btn-outline-secondary" %> 
        <% if policy(discount).destroy? %>
          <%= button_to "Destroy this discount", discount, method: :delete, class: "btn btn-outline-danger" %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/discounts/new.html.erb
<h1>New discount</h1>

<%= render "form", discount: @discount %>

<br>